---
title: "Implicit Conceptual PT Data Analysis (for SAP requirement)"
author: "Kathryn Denning"
date: "2/14/2020"
output: 
  html_document:
    code_folding: "hide"
    toc: true
    toc_float: true
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# Cleaning
## import data

#install.packages("rio")
#install.packages("here")
#install.packages("tidyverse")
#install.packages("magrittr")
#install.packages("janitor")
#install.packages("lme4")
#install.packages("psy")
#install.packages("irr")
#install.packages("emmeans")
#install.packages("sjPlot")
#install.packages("effects")
#install.packages("fs")
library(rio)
library(here)
library(tidyverse)
library(magrittr)
library(janitor)
library(lme4)
library(psy)
library(irr)
library(psych)
library(sjPlot)
library(emmeans)
library(effects)
library(here)
library(fs)

#Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r combining datasets}
# Getting file names for each individual participants datasets into one character vector
files <- dir_ls(here::here("Data"), glob = "*.csv")

# Reading one dataset in to figure out how I want to clean it
sap1 <- readr::read_csv(file = files[1],
                col_names = TRUE)

# Practice cleaning on one dataset
sap1_sub <- sap1 %>% select(participant, expBlock.thisN, expTrials.thisN, 
                            facing_exp, person_exp, food_exp, showL_R, 
                            consistent, exp_resp.keys, exp_resp.rt) %>% 
  na.omit() %>% 
  mutate(trial_num = as.numeric(row_number()),
         consistent = as.factor(consistent),
         visibility = as.factor(ifelse(facing_exp == showL_R, "same", ifelse(facing_exp != showL_R, "diff", NA))))

# Writing a function to clean all the datasets
clean_sap <- function(file) {
                    sap <- read_csv(file)
                    sap %>% 
                    select(participant, expBlock.thisN, expTrials.thisN, 
                            facing_exp, person_exp, food_exp, showL_R, 
                            consistent, exp_resp.keys, exp_resp.rt) %>% 
  na.omit() %>% 
  mutate(trial_num = as.numeric(row_number()),
         consistent = as.factor(consistent),
         visibility = as.factor(ifelse(facing_exp == showL_R, "same", ifelse(facing_exp != showL_R, "diff", NA))))
}

# Try to apply function to list of datasets to cycle through but gets error
map_df(files, clean_sap(file), .id = "column_names")

# Trying again but this time with a for loop, but same error
## creating object to put everything from the for loop into
sap_clean_files <- dir(here::here("Data"))

for (file in files) { # for every file...
    temp <- clean_sap(file)  # clean it with clean_sap() function I created
    sap_clean_files <- rbind(sap_clean_files, temp)
}

# Try to batch load data instead, to clean once it is all loaded, but also has an error
batch <- map_df(files, readr::read_csv, .id = "file")
```